name: Build
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: windows-lates
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install deps
        run : npm ci
      - name: Build project
        run : npm run build
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          path: build
          name: build-fl
  deploy:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Get build project
        uses: actions/download-artifact@v3
        with:
          name: build-fl

