name: Deploy React App
on: push
jobs:
  despicableMe:
    runs-on: windows-latest
    steps:
      - name: Get code from repo!
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test React Application  with yaml
        run: npm run test
      - name: Lint application
        run: npm run lint
      - name: Build application
        run: npm run build
      - name: Deploy
        run: echo Deploying...