name: Deploy React App
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/*'
jobs:
  despicableMe:
    runs-on: windows-latest
    steps:
      - name: Get code from repo!
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test React Application  with yaml
    lint:
      runs-on: windows-latest
      steps:
        - name: Get code from repo!
          uses: actions/checkout@v3
        - name: Install dependencies
          run: npm ci
        - name: Lint application
          run: npm run lint
    build:
      runs-on: windows-latest
      steps:
        - name: Get code from repo!
          uses: actions/checkout@v3
        - name: Install dependencies
          run: npm ci
        - name: Build application
          run: npm run build
        - name: Deploy
          run: echo Deploying...