name: print
on:
  workflow_dispatch :
  pull_request:
   types: [opened, edited, reopened]
jobs:
  print:
    runs-on: windows-latest
    steps:
      - name: Print context
        run: echo "${{ github.event }}"