name: Test React Application
on: push
jobs:
  despicableMe:
    runs-on: windows-latest
    steps:
      - name: Get code from repo!
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test React Application  with yaml
        run: npm run test